codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "85..90"
  status:
    project: # settings affecting project coverage
      enabled: yes
      tests:
      	target: 90% # auto % coverage target
      	threshold: 3%  # allow for n% reduction of coverage without failing

