codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "85..90"
  status:
    project: # settings affecting project coverage
      enabled: yes
      target: 90% # auto % coverage target
      threshold: 5%  # allow for 5% reduction of coverage without failing
