name: pangres-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - mypy
  - pytest
  - pytest-cov
  - pytest-benchmark
  - psycopg2
  - pymysql
  - tabulate
  - pip:
    - asyncpg
    - aiosqlite
    - aiomysql
    - cx_Oracle
    - npdoc_to_md
