name: pangres-dev
dependencies:
  - pip
  - pytest
  - pytest-cov
  - pytest-benchmark
  - psycopg2
  - pymysql
  - tabulate
  - pip:
    - asyncpg
    - aiosqlite
    - aiomysql
    - cx_Oracle
    - npdoc_to_md
    - pytest-asyncio
