name: pangres-dev
channels:
  - conda-forge
dependencies:
  - pip
  - psycopg2
  - pip:
    - asyncpg
    - aiosqlite
    - aiomysql
    - cx_Oracle
    - cryptography
    - flake8
    - mypy
    - npdoc_to_md
    - pymysql
    - pytest
    - pytest-benchmark
    - pytest-cov
    - tabulate
