version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.7.3
    - image: circleci/postgres:12
      environment:
        POSTGRES_USER: circleci_user
        POSTGRES_DB: circleci_test
    working_directory: ~/pangres
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
    - run:
        name: run tests
        command: |
          . venv/bin/activate
          # install package (fetches setup.py in current directory)
          pip install .
          pip install codecov
          pip install coverage
          pip install numpy
          pip install pytest
          pip install pytest-benchmark
          pip install pytest-cov
          # somehow the commented line below does not do coverage of non tests files
          # pytest pangres --cov=./
          # use this instead
          coverage run -m pytest
          codecov
workflows:
  version: 2
  workflow:
    jobs:
    - build
