version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.8
    - image: circleci/postgres:12
      environment:
        POSTGRES_USER: circleci_user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: circleci_test
    - image: mysql:latest
      environment:
        MYSQL_HOST: 127.0.0.1
        MYSQL_ROOT_HOST: "%"
        MYSQL_USER: circleci_user
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: circleci_test
    working_directory: ~/pangres
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
    - run:
        name: run tests
        command: |
          . venv/bin/activate
          # install package (fetches setup.py in current directory)
          pip install .
          pip install codecov
          pip install coverage
          pip install numpy
          pip install pytest
          pip install pytest-benchmark
          pip install pytest-cov
          pytest -s -v pangres --cov=./ --conn_string=sqlite:///:memory:
          pytest -s -v pangres --cov=./ --conn_string=postgresql://circleci_user:password@localhost:5432/circleci_test?sslmode=disable
          pytest -s -v pangres --cov=./ --conn_string=mysql://circleci_user:password@127.0.0.1:3306/circleci_test
          codecov
workflows:
  version: 2
  workflow:
    jobs:
    - build
